site_name: DataLitMT
nav:
  - Home: index.md
  - Literature: literature.md
  - Frameworks: framework.md
  - Categories: categories.md
  - Learning Resources: resources.md
theme:
  name: readthedocs
  #name: gitbook
  #name: null
  #custom_dir: 'minimal-theme/'
extra_css:
  - extra.css
use_directory_urls: true
plugins:
  #- jekyll-remote-theme
  - search:
      lang: de
dev_addr: '0.0.0.0:8080'

